### ISSUE TITLE
[SOLVED] error 404 when installing

### ISSUE THREAD

**Issue by ghost** [yosulramp/material-color-palette-js#1]
the correct package name with npm is `@yosulramp/material-color-palette-js`

`npm install @yosulramp/material-color-palette-js` works

`npm install material-color-palette-js` gives error 404

here [https://github.com/yosulramp/material-color-palette-js](https://github.com/yosulramp/material-color-palette-js) is written incorrectly

**Comment by binarydiver** [comment]
Thank you.
I am fixed README with `material-color-palette-js` >> `@yosulramp/material-color-palette-js`
